# Generated by Django 4.1.1 on 2022-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0002_remove_cliente_id_cliente_direccion_cliente_movil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='alta',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='movil',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
