# Generated by Django 4.1.1 on 2022-11-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0003_remove_cliente_alta_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('ventas', models.IntegerField()),
            ],
        ),
    ]
