# Generated by Django 4.1.1 on 2022-11-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0005_vinilo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinilo',
            name='precio',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
