# Generated by Django 4.1.1 on 2022-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0006_vinilo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinilo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
